export const API_ROOT_URL = 'http://localhost:3090';

/*          Photos          */ 

export const GET_PHOTOS = 'GET_PHOTOS';
export const GET_PHOTOS_SUCCESS = 'GET_PHOTOS_SUCCESS';
export const GET_PHOTOS_FAILURE = 'GET_PHOTOS_FAILURE';

export const ASSIGN_CATEGORY = 'ASSIGN_CATEGORY';
export const ASSIGN_CATEGORY_SUCCESS = 'ASSIGN_CATEGORY_SUCCESS';
export const ASSIGN_CATEGORY_FAILURE = 'ASSIGN_CATEGORY_FAILURE';

export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS';
export const UPLOAD_PHOTO_ERROR = 'UPLOAD_PHOTO_ERROR';


/*          Categories          */ 
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILURE = 'GET_CATEGORIES_FAILURE';


export const ADD_CATEGORY =  'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS =  'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILURE =  'ADD_CATEGORY_FAILURE';


export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const REMOVE_CATEGORY_SUCCESS = 'REMOVE_CATEGORY_SUCCESS';
export const REMOVE_CATEGORY_FAILURE = 'REMOVE_CATEGORY_FAILURE';

export const SET_CATEGORY = 'SET_CATEGORY';